volumes:
  runner-cache:

services:
  runner:
    restart: always
    image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine
    volumes:
      - ./config:/etc/gitlab-runner:rw
      - runner-cache:/cache
      - /var/run/docker.sock:/var/run/docker.sock